apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "chroma-cluster.coordinator.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-coordinator
{{- if .Values.image.pullSecrets }}
imagePullSecrets:
  - name: {{ .Values.image.pullSecrets }}
{{- end}}
